services:
  backend:
    #TODO
  frontend:
    #TODO
  pg:
    # ПОТОМ ПЕРЕНЕСТИ ПЕРЕМЕННЫЕ В env
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    #TODO