FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./

COPY packages/backend ./packages/backend
COPY packages/shared ./packages/shared
COPY packages/types ./packages/types

RUN npm install

COPY . .

EXPOSE 80

CMD ["npm", "run", "dev"]
# docker build -t znakomstva-back -f Dockerfile.back .
# docker run --name znakomstva-back -p 3000:80 znakomstva-back